# Generated by Django 5.2.17 on 2026-08-26 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (mínimo 3 caracteres)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(help_text='Código único de la categoría (ej: COMP, PERIF)', max_length=10, unique=True, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está activa o inactiva', verbose_name='¿Está Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Se asigna automáticamente al crear', verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente al modificar', verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'inventario_categoria',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_categoria_nombre'), models.Index(fields=['codigo'], name='idx_categoria_codigo')],
            },
        ),
    ]
