# Generated by Django 5.2.17 on 2026-09-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(help_text='Código único (ej: ACT-2024-001)', max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='activos/fotos/%Y/%m/', verbose_name='Fotografía')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.categoria', verbose_name='Categoría')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.estado', verbose_name='Estado')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventario.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'inventario_activo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
