# Generated by Django 5.2.17 on 2026-09-11 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_historialmovimiento_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('COORD', 'Coordinador'), ('TEC', 'Técnico'), ('AUX', 'Auxiliar')], default='AUX', max_length=10)),
                ('departamento', models.CharField(choices=[('TI', 'Tecnología e Informática'), ('ADM', 'Administrativo'), ('MTO', 'Mantenimiento'), ('LOG', 'Logística')], default='TI', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['usuario__username'],
            },
        ),
    ]
