# Generated by Django 5.2.17 on 2026-09-11 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_repr', models.CharField(blank=True, max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='inventario__fecha_h_ccf3f7_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='inventario__usuario_441826_idx'), models.Index(fields=['modelo', '-fecha_hora'], name='inventario__modelo_cff00b_idx')],
            },
        ),
    ]
