# Generated by Django 5.2.17 on 2026-09-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, default='', help_text='Breve descripción del usuario', verbose_name='Biografía'),
        ),
    ]
