# Generated by Django 5.2.17 on 2026-08-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la ubicación', max_length=100, unique=True, verbose_name='Nombre de la Ubicación')),
                ('tipo', models.CharField(choices=[('BODEGA', 'Bodega'), ('LABORATORIO', 'Laboratorio'), ('OFICINA', 'Oficina'), ('TALLER', 'Taller')], default='BODEGA', help_text='Tipo de espacio físico', max_length=20, verbose_name='Tipo de Ubicación')),
                ('codigo', models.CharField(help_text='Código único (ej: BOD-01, LAB-02)', max_length=20, unique=True, verbose_name='Código')),
                ('capacidad', models.IntegerField(default=0, help_text='Número máximo de activos', verbose_name='Capacidad')),
                ('responsable', models.CharField(blank=True, help_text='Nombre del responsable', max_length=100, null=True, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'inventario_ubicacion',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_ubicacion_nombre'), models.Index(fields=['codigo'], name='idx_ubicacion_codigo')],
            },
        ),
    ]
