# Generated by Django 5.2.17 on 2026-08-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Estado')),
                ('codigo', models.CharField(help_text='Código único (ej: OPER, MANT, REP)', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6c757d', help_text='Color hexadecimal (ej: #28a745)', max_length=7, verbose_name='Color')),
                ('es_operativo', models.BooleanField(default=True, help_text='¿El activo en este estado está operativo?', verbose_name='Es Operativo')),
                ('requiere_accion', models.BooleanField(default=False, help_text='¿Requiere alguna acción o seguimiento?', verbose_name='Requiere Acción')),
                ('orden', models.IntegerField(default=0, help_text='Orden de prioridad (menor = más prioritario)', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'inventario_estado',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
