# Generated by Django 5.2.17 on 2026-09-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuario')),
                ('motivo', models.CharField(choices=[('TRASLADO', 'Traslado Normal'), ('MANTENIMIENTO', 'Envío a Mantenimiento'), ('PRESTAMO', 'Préstamo Temporal'), ('REASIGNACION', 'Reasignación Permanente'), ('DEVOLUCION', 'Devolución'), ('OTRO', 'Otro Motivo')], default='TRASLADO', max_length=20, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('aprobado', models.BooleanField(default=True, verbose_name='Aprobado')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='inventario.activo', verbose_name='Activo')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.ubicacion', verbose_name='Ubicación Destino')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.ubicacion', verbose_name='Ubicación Origen')),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'db_table': 'inventario_historial_movimiento',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo')], max_length=20, verbose_name='Tipo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('tecnico', models.CharField(max_length=200, verbose_name='Técnico')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('repuestos', models.TextField(blank=True, null=True, verbose_name='Repuestos')),
                ('estado_mantenimiento', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'inventario_mantenimiento',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
